import csv
import time
import json
import threading
import random
import paho.mqtt.client as mqtt
import os
from dotenv import load_dotenv

load_dotenv()

# --- CONFIGURATION ---
BROKER = os.getenv("MQTT_BROKER")
PORT = int(os.getenv("MQTT_PORT", "8883"))
TOPIC = os.getenv("MQTT_TOPIC")
CSV_FILE = "../../campus_route.csv"

# --- GLOBAL STATE ---
# States: "NORMAL", "THROTTLED", "OFFLINE"
current_state = "NORMAL"
offline_buffer = []
throttled_buffer = []

def load_route():
    """Loads the CSV generated by the OSRM script."""
    route = []
    with open(CSV_FILE, 'r') as file:
        reader = csv.DictReader(file)
        for row in reader:
            route.append({"lat": float(row['lat']), "lng": float(row['lng'])})
    return route

def keyboard_listener():
    """Runs in a background thread to listen for your commands during the demo."""
    global current_state
    print("\n--- 🎮 LIVE DEMO CONTROLS ---")
    print("Type 'n' + Enter -> NORMAL Mode")
    print("Type 't' + Enter -> THROTTLED Mode (Sends batch every 10s)")
    print("Type 'o' + Enter -> OFFLINE Mode (Simulates tunnel/drop, buffers data)")
    print("------------------------------\n")
    
    while True:
        cmd = input().strip().lower()
        if cmd == 'n':
            print("\n🟢 [STATE CHANGE] -> NORMAL BANDWIDTH")
            current_state = "NORMAL"
        elif cmd == 't':
            print("\n🟡 [STATE CHANGE] -> THROTTLED BANDWIDTH")
            current_state = "THROTTLED"
        elif cmd == 'o':
            print("\n🔴 [STATE CHANGE] -> OFFLINE (Signal Lost!)")
            current_state = "OFFLINE"

def main():
    global current_state, offline_buffer, throttled_buffer
    
    # 1. Setup MQTT
    client = mqtt.Client(client_id="bhu_bus_simulator_1_test", clean_session=True)
    client.tls_set()
    client.username_pw_set(os.getenv("MQTT_USERNAME"), os.getenv("MQTT_PASSWORD"))
    
    client.connect(BROKER, PORT)
    client.loop_start()
    
    # 2. Load the route
    route = load_route()
    print(f"Loaded {len(route)} waypoints. Starting engine...")
    
    # 3. Start the keyboard listener thread
    listener = threading.Thread(target=keyboard_listener, daemon=True)
    listener.start()
    
    # 4. The Main Driving Loop
    waypoint_index = 0
    
    while True:
        # Get current location and simulate realistic speed (e.g., 35-45 km/h)
        current_location = route[waypoint_index]
        payload = {
            "bus_id": "bus_1",
            "lat": current_location['lat'],
            "lng": current_location['lng'],
            "speed_kmh": random.randint(35, 45),
            "timestamp": int(time.time())
        }
        
        # --- STATE MACHINE LOGIC ---
        
        if current_state == "NORMAL":
            # If we just came back online, flush the offline buffer first!
            if len(offline_buffer) > 0:
                print(f"🚀 [RECOVERY] Flushing {len(offline_buffer)} offline points to server!")
                recovery_payload = {
                    "type": "recovery",
                    "bus_id": "1",
                    "history": offline_buffer,
                    "current": payload
                }
                client.publish(TOPIC, json.dumps(recovery_payload), qos=1)
                offline_buffer = [] # Clear buffer
            
            # Send normal ping
            print(f"📡 [NORMAL] Pinging location: {payload['lat']}, {payload['lng']}")
            client.publish(TOPIC, json.dumps({"type": "live", **payload}), qos=0)
            
        elif current_state == "THROTTLED":
            # Add to temporary buffer
            throttled_buffer.append(payload)
            print(f"⏳ [THROTTLED] Buffering point... ({len(throttled_buffer)}/5)")
            
            # Send a compressed batch every 5 points (10 seconds)
            if len(throttled_buffer) >= 5:
                print("📦 [THROTTLED] Sending compressed batch payload!")
                batch_payload = {
                    "type": "batch",
                    "bus_id": "bus_1",
                    "data": throttled_buffer
                }
                client.publish(TOPIC, json.dumps(batch_payload), qos=1)
                throttled_buffer = [] # Clear buffer

        elif current_state == "OFFLINE":
            # Do not send anything. Just store it.
            offline_buffer.append(payload)
            print(f"🛑 [OFFLINE] No signal. Saving to local buffer. (Size: {len(offline_buffer)})")

        # Move to next waypoint (loop back to start if at the end)
        waypoint_index = (waypoint_index + 1) % len(route)
        
        # Simulate bus driving time (2 seconds between GPS pings)
        time.sleep(2)

if __name__ == "__main__":
    main()
